"""Criacao inicial

Revision ID: 62a1cbe80c13
Revises: 
Create Date: 2026-05-15 11:18:55.908396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a1cbe80c13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('crm', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicos_crm'), 'medicos', ['crm'], unique=True)
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_crm'), table_name='medicos')
    op.drop_table('medicos')
    # ### end Alembic commands ###
